-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.fb_player_match_stats (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  match_id uuid NOT NULL,
  player_id uuid NOT NULL,
  team_id uuid NOT NULL,
  player_name text NOT NULL DEFAULT ''::text,
  goals integer NOT NULL DEFAULT 0,
  assists integer NOT NULL DEFAULT 0,
  shots_on integer NOT NULL DEFAULT 0,
  shots_off integer NOT NULL DEFAULT 0,
  fouls_committed integer NOT NULL DEFAULT 0,
  fouls_drawn integer NOT NULL DEFAULT 0,
  yellow_cards integer NOT NULL DEFAULT 0,
  red_cards integer NOT NULL DEFAULT 0,
  saves integer NOT NULL DEFAULT 0,
  blocks integer NOT NULL DEFAULT 0,
  interceptions integer NOT NULL DEFAULT 0,
  clearances integer NOT NULL DEFAULT 0,
  dribbles integer NOT NULL DEFAULT 0,
  chances_created integer NOT NULL DEFAULT 0,
  minutes_played integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT fb_player_match_stats_pkey PRIMARY KEY (id),
  CONSTRAINT fb_player_match_stats_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.ls_matches(id),
  CONSTRAINT fb_player_match_stats_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.players(id),
  CONSTRAINT fb_player_match_stats_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.fb_player_tournament_stats (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tournament_id uuid NOT NULL,
  player_id uuid NOT NULL,
  team_id uuid NOT NULL,
  player_name text NOT NULL DEFAULT ''::text,
  matches_played integer NOT NULL DEFAULT 0,
  goals integer NOT NULL DEFAULT 0,
  assists integer NOT NULL DEFAULT 0,
  shots_on integer NOT NULL DEFAULT 0,
  shots_off integer NOT NULL DEFAULT 0,
  fouls integer NOT NULL DEFAULT 0,
  yellow_cards integer NOT NULL DEFAULT 0,
  red_cards integer NOT NULL DEFAULT 0,
  saves integer NOT NULL DEFAULT 0,
  blocks integer NOT NULL DEFAULT 0,
  interceptions integer NOT NULL DEFAULT 0,
  clearances integer NOT NULL DEFAULT 0,
  dribbles integer NOT NULL DEFAULT 0,
  chances_created integer NOT NULL DEFAULT 0,
  clean_sheets integer NOT NULL DEFAULT 0,
  rating_score numeric NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT fb_player_tournament_stats_pkey PRIMARY KEY (id),
  CONSTRAINT fb_player_tournament_stats_tournament_id_fkey FOREIGN KEY (tournament_id) REFERENCES public.ls_tournaments(id),
  CONSTRAINT fb_player_tournament_stats_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.players(id),
  CONSTRAINT fb_player_tournament_stats_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.ls_balls (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  innings_id uuid NOT NULL,
  over_number smallint NOT NULL,
  ball_number smallint NOT NULL,
  sequence integer NOT NULL,
  batter_id uuid NOT NULL,
  non_striker_id uuid NOT NULL,
  bowler_id uuid NOT NULL,
  runs_bat smallint NOT NULL DEFAULT 0,
  runs_extra smallint NOT NULL DEFAULT 0,
  extra_type text CHECK (extra_type IS NULL OR (extra_type = ANY (ARRAY['wide'::text, 'no_ball'::text, 'bye'::text, 'leg_bye'::text, 'penalty'::text]))),
  is_wicket boolean NOT NULL DEFAULT false,
  wicket_type USER-DEFINED,
  wicket_player_id uuid,
  fielder_id uuid,
  is_legal boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ls_balls_pkey PRIMARY KEY (id),
  CONSTRAINT ls_balls_innings_id_fkey FOREIGN KEY (innings_id) REFERENCES public.ls_innings(id),
  CONSTRAINT ls_balls_batter_id_fkey FOREIGN KEY (batter_id) REFERENCES public.players(id),
  CONSTRAINT ls_balls_non_striker_id_fkey FOREIGN KEY (non_striker_id) REFERENCES public.players(id),
  CONSTRAINT ls_balls_bowler_id_fkey FOREIGN KEY (bowler_id) REFERENCES public.players(id),
  CONSTRAINT ls_balls_wicket_player_id_fkey FOREIGN KEY (wicket_player_id) REFERENCES public.players(id),
  CONSTRAINT ls_balls_fielder_id_fkey FOREIGN KEY (fielder_id) REFERENCES public.players(id)
);
CREATE TABLE public.ls_batting_stats (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  innings_id uuid NOT NULL,
  player_id uuid NOT NULL,
  runs integer NOT NULL DEFAULT 0,
  balls_faced integer NOT NULL DEFAULT 0,
  fours integer NOT NULL DEFAULT 0,
  sixes integer NOT NULL DEFAULT 0,
  is_out boolean NOT NULL DEFAULT false,
  dismissal_type USER-DEFINED,
  dismissal_bowler_id uuid,
  dismissal_fielder_id uuid,
  batting_position smallint,
  CONSTRAINT ls_batting_stats_pkey PRIMARY KEY (id),
  CONSTRAINT ls_batting_stats_innings_id_fkey FOREIGN KEY (innings_id) REFERENCES public.ls_innings(id),
  CONSTRAINT ls_batting_stats_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.players(id),
  CONSTRAINT ls_batting_stats_dismissal_bowler_id_fkey FOREIGN KEY (dismissal_bowler_id) REFERENCES public.players(id),
  CONSTRAINT ls_batting_stats_dismissal_fielder_id_fkey FOREIGN KEY (dismissal_fielder_id) REFERENCES public.players(id)
);
CREATE TABLE public.ls_bowling_stats (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  innings_id uuid NOT NULL,
  player_id uuid NOT NULL,
  overs numeric NOT NULL DEFAULT 0,
  maidens integer NOT NULL DEFAULT 0,
  runs_conceded integer NOT NULL DEFAULT 0,
  wickets integer NOT NULL DEFAULT 0,
  wides integer NOT NULL DEFAULT 0,
  no_balls integer NOT NULL DEFAULT 0,
  dot_balls integer NOT NULL DEFAULT 0,
  CONSTRAINT ls_bowling_stats_pkey PRIMARY KEY (id),
  CONSTRAINT ls_bowling_stats_innings_id_fkey FOREIGN KEY (innings_id) REFERENCES public.ls_innings(id),
  CONSTRAINT ls_bowling_stats_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.players(id)
);
CREATE TABLE public.ls_events (
  id bigint NOT NULL DEFAULT nextval('ls_events_id_seq'::regclass),
  match_id uuid,
  sport USER-DEFINED,
  type text,
  payload jsonb,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT ls_events_pkey PRIMARY KEY (id),
  CONSTRAINT ls_events_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.ls_matches(id)
);
CREATE TABLE public.ls_innings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  match_id uuid NOT NULL,
  innings_number smallint NOT NULL CHECK (innings_number = ANY (ARRAY[1, 2])),
  batting_team_id uuid NOT NULL,
  bowling_team_id uuid NOT NULL,
  total_runs integer NOT NULL DEFAULT 0,
  total_wickets integer NOT NULL DEFAULT 0,
  total_overs numeric NOT NULL DEFAULT 0,
  total_extras integer NOT NULL DEFAULT 0,
  status USER-DEFINED NOT NULL DEFAULT 'not_started'::innings_status,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ls_innings_pkey PRIMARY KEY (id),
  CONSTRAINT ls_innings_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.ls_matches(id),
  CONSTRAINT ls_innings_batting_team_id_fkey FOREIGN KEY (batting_team_id) REFERENCES public.teams(id),
  CONSTRAINT ls_innings_bowling_team_id_fkey FOREIGN KEY (bowling_team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.ls_match_state (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  match_id uuid NOT NULL UNIQUE,
  current_innings_id uuid,
  striker_id uuid,
  non_striker_id uuid,
  current_bowler_id uuid,
  current_over smallint NOT NULL DEFAULT 0,
  current_ball smallint NOT NULL DEFAULT 0,
  last_ball_id uuid,
  partnership_runs integer NOT NULL DEFAULT 0,
  partnership_balls integer NOT NULL DEFAULT 0,
  score_runs integer NOT NULL DEFAULT 0,
  score_wickets integer NOT NULL DEFAULT 0,
  score_overs numeric NOT NULL DEFAULT 0,
  score_extras integer NOT NULL DEFAULT 0,
  balls_this_over jsonb DEFAULT '[]'::jsonb,
  striker_snapshot jsonb,
  non_striker_snapshot jsonb,
  bowler_snapshot jsonb,
  last_event text,
  target_score integer,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  state jsonb,
  is_paused boolean DEFAULT false,
  stats jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT ls_match_state_pkey PRIMARY KEY (id),
  CONSTRAINT ls_match_state_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.ls_matches(id),
  CONSTRAINT ls_match_state_current_innings_id_fkey FOREIGN KEY (current_innings_id) REFERENCES public.ls_innings(id),
  CONSTRAINT ls_match_state_striker_id_fkey FOREIGN KEY (striker_id) REFERENCES public.players(id),
  CONSTRAINT ls_match_state_non_striker_id_fkey FOREIGN KEY (non_striker_id) REFERENCES public.players(id),
  CONSTRAINT ls_match_state_current_bowler_id_fkey FOREIGN KEY (current_bowler_id) REFERENCES public.players(id),
  CONSTRAINT ls_match_state_last_ball_id_fkey FOREIGN KEY (last_ball_id) REFERENCES public.ls_balls(id)
);
CREATE TABLE public.ls_matches (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tournament_id uuid NOT NULL,
  team_a_id uuid,
  team_b_id uuid,
  status USER-DEFINED NOT NULL DEFAULT 'scheduled'::match_status,
  start_time timestamp with time zone,
  venue text,
  settings jsonb NOT NULL DEFAULT '{}'::jsonb,
  result jsonb,
  toss jsonb,
  playing_xi jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ls_matches_pkey PRIMARY KEY (id),
  CONSTRAINT ls_matches_tournament_id_fkey FOREIGN KEY (tournament_id) REFERENCES public.ls_tournaments(id),
  CONSTRAINT ls_matches_team_a_id_fkey FOREIGN KEY (team_a_id) REFERENCES public.teams(id),
  CONSTRAINT ls_matches_team_b_id_fkey FOREIGN KEY (team_b_id) REFERENCES public.teams(id)
);
CREATE TABLE public.ls_tournament_teams (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tournament_id uuid NOT NULL,
  team_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ls_tournament_teams_pkey PRIMARY KEY (id),
  CONSTRAINT ls_tournament_teams_tournament_id_fkey FOREIGN KEY (tournament_id) REFERENCES public.ls_tournaments(id),
  CONSTRAINT ls_tournament_teams_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.ls_tournaments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  sport text NOT NULL CHECK (sport = ANY (ARRAY['cricket'::text, 'football'::text, 'badminton'::text])),
  location text,
  start_date date,
  end_date date,
  status text NOT NULL DEFAULT 'upcoming'::text CHECK (status = ANY (ARRAY['upcoming'::text, 'active'::text, 'completed'::text, 'cancelled'::text])),
  settings jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ls_tournaments_pkey PRIMARY KEY (id),
  CONSTRAINT ls_tournaments_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.players (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  auction_id uuid,
  team_id uuid,
  name text NOT NULL,
  role text NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'upcoming'::player_status,
  sold_price numeric,
  sold_team_id uuid,
  jersey_number integer,
  photo_url text,
  is_captain boolean DEFAULT false,
  is_blind_bid boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  match_stats jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT players_pkey PRIMARY KEY (id),
  CONSTRAINT players_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT players_sold_team_id_fkey FOREIGN KEY (sold_team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text NOT NULL,
  role text NOT NULL DEFAULT 'viewer'::text CHECK (role = ANY (ARRAY['admin'::text, 'viewer'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  active_device_id text,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.teams (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  auction_id uuid,
  name text NOT NULL,
  manager text DEFAULT ''::text,
  purse_remaining numeric DEFAULT 0,
  slots_remaining integer DEFAULT 0,
  captain_id uuid,
  logo_url text,
  sport text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT teams_pkey PRIMARY KEY (id),
  CONSTRAINT teams_captain_id_fkey FOREIGN KEY (captain_id) REFERENCES public.players(id)
);